// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: qrcode/cmd/grpcapps/pob/dino.proto

package pob

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CPAccessPolicy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PortalAccounts []*CPAccessPolicy_PortalAccounts `protobuf:"bytes,1,rep,name=portalAccounts,proto3" json:"portalAccounts,omitempty"`
}

func (x *CPAccessPolicy) Reset() {
	*x = CPAccessPolicy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPAccessPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPAccessPolicy) ProtoMessage() {}

func (x *CPAccessPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPAccessPolicy.ProtoReflect.Descriptor instead.
func (*CPAccessPolicy) Descriptor() ([]byte, []int) {
	return file_qrcode_cmd_grpcapps_pob_dino_proto_rawDescGZIP(), []int{0}
}

func (x *CPAccessPolicy) GetPortalAccounts() []*CPAccessPolicy_PortalAccounts {
	if x != nil {
		return x.PortalAccounts
	}
	return nil
}

type CPAccessPolicy_PortalAccounts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string                                    `protobuf:"bytes,1,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Policies   []*CPAccessPolicy_PortalAccounts_Policies `protobuf:"bytes,2,rep,name=policies,proto3" json:"policies,omitempty"`
}

func (x *CPAccessPolicy_PortalAccounts) Reset() {
	*x = CPAccessPolicy_PortalAccounts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPAccessPolicy_PortalAccounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPAccessPolicy_PortalAccounts) ProtoMessage() {}

func (x *CPAccessPolicy_PortalAccounts) ProtoReflect() protoreflect.Message {
	mi := &file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPAccessPolicy_PortalAccounts.ProtoReflect.Descriptor instead.
func (*CPAccessPolicy_PortalAccounts) Descriptor() ([]byte, []int) {
	return file_qrcode_cmd_grpcapps_pob_dino_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CPAccessPolicy_PortalAccounts) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CPAccessPolicy_PortalAccounts) GetPolicies() []*CPAccessPolicy_PortalAccounts_Policies {
	if x != nil {
		return x.Policies
	}
	return nil
}

type CPAccessPolicy_PortalAccounts_Policies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role        string                                                `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	AssetGroups []*CPAccessPolicy_PortalAccounts_Policies_AssetGroups `protobuf:"bytes,2,rep,name=assetGroups,proto3" json:"assetGroups,omitempty"`
}

func (x *CPAccessPolicy_PortalAccounts_Policies) Reset() {
	*x = CPAccessPolicy_PortalAccounts_Policies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPAccessPolicy_PortalAccounts_Policies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPAccessPolicy_PortalAccounts_Policies) ProtoMessage() {}

func (x *CPAccessPolicy_PortalAccounts_Policies) ProtoReflect() protoreflect.Message {
	mi := &file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPAccessPolicy_PortalAccounts_Policies.ProtoReflect.Descriptor instead.
func (*CPAccessPolicy_PortalAccounts_Policies) Descriptor() ([]byte, []int) {
	return file_qrcode_cmd_grpcapps_pob_dino_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *CPAccessPolicy_PortalAccounts_Policies) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CPAccessPolicy_PortalAccounts_Policies) GetAssetGroups() []*CPAccessPolicy_PortalAccounts_Policies_AssetGroups {
	if x != nil {
		return x.AssetGroups
	}
	return nil
}

type CPAccessPolicy_PortalAccounts_Policies_AssetGroups struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CPAccessPolicy_PortalAccounts_Policies_AssetGroups) Reset() {
	*x = CPAccessPolicy_PortalAccounts_Policies_AssetGroups{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CPAccessPolicy_PortalAccounts_Policies_AssetGroups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPAccessPolicy_PortalAccounts_Policies_AssetGroups) ProtoMessage() {}

func (x *CPAccessPolicy_PortalAccounts_Policies_AssetGroups) ProtoReflect() protoreflect.Message {
	mi := &file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPAccessPolicy_PortalAccounts_Policies_AssetGroups.ProtoReflect.Descriptor instead.
func (*CPAccessPolicy_PortalAccounts_Policies_AssetGroups) Descriptor() ([]byte, []int) {
	return file_qrcode_cmd_grpcapps_pob_dino_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *CPAccessPolicy_PortalAccounts_Policies_AssetGroups) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CPAccessPolicy_PortalAccounts_Policies_AssetGroups) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_qrcode_cmd_grpcapps_pob_dino_proto protoreflect.FileDescriptor

var file_qrcode_cmd_grpcapps_pob_dino_proto_rawDesc = []byte{
	0x0a, 0x22, 0x71, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x70, 0x6f, 0x62, 0x2f, 0x64, 0x69, 0x6e, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x6f, 0x62, 0x22, 0x87, 0x03, 0x0a, 0x0e, 0x43, 0x50,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x4a, 0x0a, 0x0e,
	0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x6f, 0x62, 0x2e, 0x43, 0x50, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x52, 0x0e, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x1a, 0xa8, 0x02, 0x0a, 0x0e, 0x50, 0x6f, 0x72,
	0x74, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x47, 0x0a, 0x08, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x70, 0x6f, 0x62, 0x2e, 0x43, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x69, 0x65, 0x73, 0x1a, 0xac, 0x01, 0x0a, 0x08, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x59, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x70, 0x6f, 0x62,
	0x2e, 0x43, 0x50, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2e,
	0x50, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x52, 0x0b, 0x61, 0x73, 0x73, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x1a, 0x31, 0x0a, 0x0b, 0x41, 0x73, 0x73, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x42, 0x05, 0x5a, 0x03, 0x70, 0x6f, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_qrcode_cmd_grpcapps_pob_dino_proto_rawDescOnce sync.Once
	file_qrcode_cmd_grpcapps_pob_dino_proto_rawDescData = file_qrcode_cmd_grpcapps_pob_dino_proto_rawDesc
)

func file_qrcode_cmd_grpcapps_pob_dino_proto_rawDescGZIP() []byte {
	file_qrcode_cmd_grpcapps_pob_dino_proto_rawDescOnce.Do(func() {
		file_qrcode_cmd_grpcapps_pob_dino_proto_rawDescData = protoimpl.X.CompressGZIP(file_qrcode_cmd_grpcapps_pob_dino_proto_rawDescData)
	})
	return file_qrcode_cmd_grpcapps_pob_dino_proto_rawDescData
}

var file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_qrcode_cmd_grpcapps_pob_dino_proto_goTypes = []interface{}{
	(*CPAccessPolicy)(nil),                                     // 0: pob.CPAccessPolicy
	(*CPAccessPolicy_PortalAccounts)(nil),                      // 1: pob.CPAccessPolicy.PortalAccounts
	(*CPAccessPolicy_PortalAccounts_Policies)(nil),             // 2: pob.CPAccessPolicy.PortalAccounts.Policies
	(*CPAccessPolicy_PortalAccounts_Policies_AssetGroups)(nil), // 3: pob.CPAccessPolicy.PortalAccounts.Policies.AssetGroups
}
var file_qrcode_cmd_grpcapps_pob_dino_proto_depIdxs = []int32{
	1, // 0: pob.CPAccessPolicy.portalAccounts:type_name -> pob.CPAccessPolicy.PortalAccounts
	2, // 1: pob.CPAccessPolicy.PortalAccounts.policies:type_name -> pob.CPAccessPolicy.PortalAccounts.Policies
	3, // 2: pob.CPAccessPolicy.PortalAccounts.Policies.assetGroups:type_name -> pob.CPAccessPolicy.PortalAccounts.Policies.AssetGroups
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_qrcode_cmd_grpcapps_pob_dino_proto_init() }
func file_qrcode_cmd_grpcapps_pob_dino_proto_init() {
	if File_qrcode_cmd_grpcapps_pob_dino_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CPAccessPolicy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CPAccessPolicy_PortalAccounts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CPAccessPolicy_PortalAccounts_Policies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CPAccessPolicy_PortalAccounts_Policies_AssetGroups); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qrcode_cmd_grpcapps_pob_dino_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qrcode_cmd_grpcapps_pob_dino_proto_goTypes,
		DependencyIndexes: file_qrcode_cmd_grpcapps_pob_dino_proto_depIdxs,
		MessageInfos:      file_qrcode_cmd_grpcapps_pob_dino_proto_msgTypes,
	}.Build()
	File_qrcode_cmd_grpcapps_pob_dino_proto = out.File
	file_qrcode_cmd_grpcapps_pob_dino_proto_rawDesc = nil
	file_qrcode_cmd_grpcapps_pob_dino_proto_goTypes = nil
	file_qrcode_cmd_grpcapps_pob_dino_proto_depIdxs = nil
}
